// Post Nombre en un ID
export const POST_PET_DATA_PENDING = "POST_PET_DATA_PENDING";
export const POST_PET_DATA_SUCCESS = "POST_PET_DATA_SUCCESS";
export const POST_PET_DATA_REJECTED = "POST_PET_DATA_REJECTED";

//Obtener una mascota por ID
export const GET_PET_REQUEST = 'FETCH_PET_REQUEST';
export const GET_PET_SUCCESS = 'FETCH_PET_SUCCESS';
export const GET_PET_FAILURE = 'FETCH_PET_FAILURE';

//Acciones
export const ACTION_PET_REQUEST = 'ACTION_PET_REQUEST';
export const ACTION_PET_SUCCESS = 'ACTION_PET_SUCCESS';
export const ACTION_PET_FAILURE = 'ACTION_PET_FAILURE';
